backend:
  name: github
  repo: siruththondan/blog-content   # EXACT repo
  branch: main
  #base_url: https://siruththondan.in # PKCE client.html hostname (just the base domain, no path)
  auth_endpoint: /admin/client.html # PKCE client.html path
  

collections:
  - name: "blog"
    label: "Blog Posts"
    folder: "content/blog"
    create: true
    slug: "{{slug}}"
    path: "{{slug}}/index.{{lang}}"
    media_folder: ""
    public_folder: ""

    fields:
      - { label: "Language", name: "lang", widget: "select", options: ["ta", "en"] }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Draft", name: "draft", widget: "boolean", default: false }
      - { label: "Tags", name: "tags", widget: "list", required: false }
      - { label: "Body", name: "body", widget: "markdown" }
